influxdata/flux-lsp-cli

src/bin.js
Closes https://github.com/influxdata/flux-lsp-cli/issues/1
fix the ipc request logging, manually tested
=> fix(src): add ipc request logging

Makefile, bump-version.sh, tag-release.sh
=> build(release): add Makefile and split release script

bump-version.sh
=> fix(release): set upstream instead of pushing to master

package-lock.json, package.json
Change version from v0.7.4 to v0.7.5
=> build: Release v0.7.5

package-lock.json, package.json
Change version from v0.7.5 to v0.7.6
=> build: Release v0.7.6

package-lock.json, package.json
Change version from v0.7.6 to v0.7.7
=> build: Release v0.7.7

package-lock.json, package.json, tag-release.sh
- Change version from `v0.7.7` to `v0.7.8`
- Upgrade to [`flux-lsp v0.5.24`](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.24)
=> build: Release v0.7.8

package-lock.json, package.json
- Change version from v0.7.8 to v0.7.9
- Upgrade LSP to v0.5.25
=> build: Release v0.7.9

package-lock.json, package.json
Change version from v0.7.10 to v0.7.11
=> build: Release v0.7.11

package-lock.json, package.json
Change version from v0.7.12 to v0.7.13
=> build: Release v0.7.13

package-lock.json, package.json
Change version from v0.7.13 to v0.7.14
=> build: Release v0.7.14

package-lock.json, package.json
Change version from v0.7.14 to v0.7.15
=> build: Release v0.7.15

package-lock.json, package.json
Change version from v0.7.15 to v0.7.16
=> build: Release v0.7.16

bump-version.sh, package-lock.json, package.json
- Change version from v0.7.16 to v0.7.17
- Upgrade Flux LSP to [v0.5.33](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.33)
=> build: Release v0.7.17

tag-release.sh
=> chore: correct url for release notes

package-lock.json, package.json
- Change version from v0.7.17 to v0.7.18
=> build: Release v0.7.18

package-lock.json, package.json
- Change version from v0.7.19 to v0.7.20
=> build: Release v0.7.20

package-lock.json, package.json
- Change version from v0.7.20 to v0.7.21
=> build: Release v0.7.21

package-lock.json, package.json
- Change version from v0.7.21 to v0.7.22
=> build: Release v0.7.22

package-lock.json
Addresses security vulnerabilities found when running `npm install`
=> chore(npm): Run npm audit fix to address security vulnerabilities

package-lock.json, package.json
- Change version from v0.7.22 to v0.7.23
=> build: Release v0.7.23

package-lock.json, package.json
- Change version from v0.7.24 to v0.7.25
=> build: Release v0.7.25

package-lock.json, package.json
- Change version from v0.7.25 to v0.7.26
=> build: Release v0.7.26

package-lock.json, package.json
- Change version from v0.7.26 to v0.7.27
=> build: Release v0.7.27

package-lock.json, package.json
- Change version from v0.7.28 to v0.7.29
=> build: Release v0.7.29

package-lock.json, package.json
- Change version from v0.7.29 to v0.7.30
=> build: Release v0.7.30

bump-version.sh, tag-release.sh
=> chore: Make release scripts mac-compatible

package-lock.json, package.json
=> build: Release v0.7.31
